spring:
  #  sql:
  #    init:
  #      mode: always
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/cns-catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: cns-catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false #for local development
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  flyway:
    baseline-on-migrate: true

server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 15s
    threads:
      max: 200
      min-spare: 10

logging:
  level:
    inc.evil: debug
    org.zalando.logbook: trace
    net.ttddyy.dsproxy.listener: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

cns:
  greeting: Welcome to the local book catalog!

features:
  demo-data:
    enabled: true


